FROM node:16 AS BUILD
WORKDIR /app
COPY package.json ./
RUN npm install -f
COPY . ./
RUN npm run build

FROM nginx:alpine
COPY --from=BUILD /app/build/ /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]